server.port: 8081
logging.level.org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_jdbc
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

easy.security.oauth2server.source:
  client: memory
  user: jdbc